# Generated by Django 4.1.4 on 2023-01-11 10:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('marketplace', '0002_tax'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Tax',
        ),
    ]
